- name: copy prometheus file
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: start prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted

- name: Wait for Prometheus is started or not
  ansible.builtin.wait_for:
    port: 9090
    delay: 10
    timeout: 30
